# modules/database.py
import json
from pathlib import Path
import pandas as pd
from datetime import datetime

# Path to the JSON file that stores all session records.
DB_PATH = Path("sessions.json")

def init_db(path: str | Path = DB_PATH):
    """
    Ensure that the database file exists before any read/write operations.
    If the file does not exist, it initializes it with an empty JSON list.
    """
    p = Path(path)
    if not p.exists():
        p.write_text("[]")

def insert_session(text_emotion: str, audio_stats: dict, gpt_score: float, gpt_feedback: str = ""):
    """
    Insert a new session record into the sessions.json file.

    Parameters:
        text_emotion (str): Emotion detected from the user's text.
        audio_stats (dict): Dictionary containing audio feature values such as pitch, energy, etc.
        gpt_score (float): Feedback score generated by GPT.
        gpt_feedback (str): Optional detailed feedback generated by GPT.
    """

    # Ensure the DB file exists
    init_db(DB_PATH)

    # Load existing data
    with DB_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)

    # Create a new record
    record = {
        "timestamp": datetime.utcnow().isoformat(),  # store the current time in ISO format
        "text_emotion": text_emotion,
        "pitch": audio_stats.get("pitch", 0),
        "energy": audio_stats.get("energy", 0),
        "tempo": audio_stats.get("tempo", 0),
        "jitter": audio_stats.get("jitter", 0),
        "shimmer": audio_stats.get("shimmer", 0),
        "pauses": audio_stats.get("pauses", 0),
        "gpt_feedback": gpt_feedback,
        "gpt_score": float(gpt_score),  # ensure score is stored as a float
    }

    # Append and save the updated data
    data.append(record)
    with DB_PATH.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

def load_sessions(path: str | Path = DB_PATH) -> pd.DataFrame:
    """
    Load all session records into a pandas DataFrame.

    Parameters:
        path (str | Path): Location of the sessions JSON file.

    Returns:
        pd.DataFrame: DataFrame containing all stored session records.
    """

    p = Path(path)

    # Return empty DataFrame if file does not exist
    if not p.exists():
        return pd.DataFrame()

    # Load data safely
    with p.open("r", encoding="utf-8") as f:
        data = json.load(f)

    # Return empty DataFrame if file exists but contains no data
    if not data:
        return pd.DataFrame()

    # Convert JSON list to DataFrame
    df = pd.DataFrame(data)

    # Normalize data types
    df["gpt_score"] = pd.to_numeric(df["gpt_score"], errors="coerce").fillna(0)
    df["timestamp"] = pd.to_datetime(df["timestamp"])  # convert timestamp to datetime

    # Maintain consistent column order
    cols = [
        "timestamp", "text_emotion", "pitch", "energy", "tempo",
        "jitter", "shimmer", "pauses", "gpt_feedback", "gpt_score"
    ]

    return df.loc[:, [c for c in cols if c in df.columns]]
